### ISSUE TITLE
Refactoring moscot to include moscot.neural

### ISSUE THREAD

**Issue by MUCDK** [theislab/moscot#763]
We want to have a moscot.neural module which implements the discrete problems as equivalent neural problems. Therefore, we consecutively do the following steps:
 - [x] remove Protocol classes https://github.com/theislab/moscot/issues/765
 - [x] Move `GENOTLinProblem` to neural module #778 
 - [x] moscot.neural.base should have `NeuralOTProblem` (currently `CondOTProblem`, instead of `OTProblem` in discrete case), and the `NeuralOutput` (instead of the `OTTOutput` in discrete case), this can be adapted from the current implementation. Therefore, restructure the output into a `BaseOutput` which is the parent class of `DiscreteOTOutput` and `NeuralOTOutput` #778 
 
moscot.neural.solvers in future times should include 
  - [ ] `GenotLin`,
  - [ ]  `GenotQuad`,
  - [ ]  and `OTCFM`, 

start with `GenotLin`, because it's implemented already, and extend it to `GenotQuad`. `OTCFM` will be added later.

 - [ ] Port the dataloader (or roughly the idea of the dataloader) from CellFlow, and extend it to include quadratic terms.
 - [ ] Let's also distinguish between the data representation which we compute the coupling in, and the one which are input/output to the flow

**Comment by selmanozleyen** [comment]
hi @MUCDK https://github.com/theislab/moscot/pull/778 should fix some of the items. 

I think the best order to do the rest are:
- Porting dataloader so that it would work with all 3 solvers you mentioned (my thesis code should be enough for this). In my thesis code I yield a dictionary of `src_flow, tgt_flow, (src,tgt)_(lin,quad)` all of these are optional. But for this code I think best would be to yield `aug_flow, src_flow, tgt_flow, (src,tgt)_(lin,quad)`. This way for OTCFM we use `src_flow, tgt_flow` and for GENOT: `aug_flow, tgt_flow`. And this is very easy to implement. ps: I'd prefer calling it `aug_flow` since it was very confusing to call it `cond` since time can also be a condition.

- This will also distinguish between the data representation (the matching function and flow part).

From what I see I'd need to refactor `NeuralOTProblem` and then a bit `GenotLinSolver and Problem`. But the rest should come more easily. If I can get help with writing tests then this can speed up the progress.

**Comment by MUCDK** [comment]
Great, thanks, this makes sense.

Does `aug` stand for `augmented`?

The dataloader in the MSc is similar to CellFlow right? Then that makes sense!

Yes, once you start , @LeonStadelmann can help with tests!

I think we can get rid of `DistributionCollection` and follow the `CellFlow` data handling. and yes, `DistributionCollection` contains one distribution.

Second q: yes, all distributions are trained with the same neural network.

**Comment by selmanozleyen** [comment]
> Does aug stand for augmented?
yes
> The dataloader in the MSc is similar to CellFlow right? Then that makes sense!
yes
> I think we can get rid of DistributionCollection and follow the CellFlow data handling. and yes, DistributionCollection contains one distribution.
Just so we are on the same page currently `DistributionContainer` has a pair of distributions and `DistributionCollection` is a dictionary of pairs.

**Comment by selmanozleyen** [comment]
@MUCDK I have another question. Currently the prepare for NeuralOTProblem is like this
```python
    @wrap_prepare
    def prepare(
        self,
        policy_key: str,
        policy: Policy_t,
        xy: Mapping[str, Any],
        xx: Mapping[str, Any],
        conditions: Mapping[str, Any],
        a: Optional[str] = None,
        b: Optional[str] = None,
        subset: Optional[Sequence[Tuple[K, K]]] = None,
        reference: K = None,
        **kwargs: Any,
    ) -> "NeuralOTProblem":
```


I will update this. I currently don't know what `xx` is or if its something different that `x_attrs`. I am planning to make it very similar to `OTProblem.prepare`.  What do you think?

```python
def prepare(
        self,
        xy: Mapping[str, Any],
        x: Mapping[str, Any],
        x_flow: Mapping[str, Any],
        x_aug: Mapping[str, Any],
        y: Mapping[str, Any],
        y_flow: Mapping[str, Any],
        a: Optional[Union[bool, str, ArrayLike]] = None,
        b: Optional[Union[bool, str, ArrayLike]] = None,
        marginal_kwargs: Dict[str, Any] = types.MappingProxyType({}),
    ) -> "NeuralOTProblem":```

I also think it is better to rewrite GENOTLinSolver as a generalized `GENOTSolver`  (it should work with OTCFM as well but since its lower priority we can check if we can make it `NeuralOTSolver` later.)

**Comment by MUCDK** [comment]
`xx` would be quadratic source term. Regarding your suggestion, I would have `xy`, `x`, `y`. By default, `x_flow=None`, and then we set `x_flow=xy` for OTFM, and `x_flow=gaussian` anyways for GENOT. Also for GENOT, I would have by default `x_aug=concat(x_lin, x_quad)`, and analogously for `y`. The rest makes sense!
